name: gogo2

on:
  workflow_dispatch:

jobs:
  dori-job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello dori
        run: echo "Hello dori"

      - name: save secret
        run: export secret='babo'

      - name: echo secret
        run: echo $secret
