name: gogo

on:
  workflow_dispatch:

jobs:
  muzzi-job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello muzzi
        run: echo "Hello muzzi"

  babo-job:
    runs-on: ubuntu-latest
    steps:
      - name: say babo muzzi
        run: echo "babo muzzi"
